import { contextBridge, ipcRenderer } from 'electron'

const api = {
  getProducts: () => ipcRenderer.invoke('db:get-products'),
  getProductByBarcode: (barcode: string) => ipcRenderer.invoke('db:get-product-by-barcode', barcode),
  createProduct: (data: unknown) => ipcRenderer.invoke('db:create-product', data),
  updateProduct: (id: string, data: unknown) => ipcRenderer.invoke('db:update-product', id, data),
  deleteProduct: (id: string) => ipcRenderer.invoke('db:delete-product', id),
  createSale: (data: unknown) => ipcRenderer.invoke('db:create-sale', data),
  getSales: (clientId?: string) => ipcRenderer.invoke('db:get-sales', clientId),
  getWarehouses: () => ipcRenderer.invoke('db:get-warehouses'),
  createWarehouse: (data: unknown) => ipcRenderer.invoke('db:create-warehouse', data),
  updateWarehouse: (id: string, data: unknown) => ipcRenderer.invoke('db:update-warehouse', id, data),
  deleteWarehouse: (id: string) => ipcRenderer.invoke('db:delete-warehouse', id),
  selectLogo: () => ipcRenderer.invoke('dialog:select-logo'),
  saveLogo: (sourcePath: string, warehouseId: string) => ipcRenderer.invoke('file:save-logo', sourcePath, warehouseId),
  saveInvoiceLogo: (sourcePath: string, warehouseId: string) => ipcRenderer.invoke('file:save-invoice-logo', sourcePath, warehouseId),
  saveProductImage: (sourcePath: string, productId: string) => ipcRenderer.invoke('file:save-product-image', sourcePath, productId),
  getStockAlerts: () => ipcRenderer.invoke('db:get-stock-alerts'),
  getPrinters: () => ipcRenderer.invoke('printer:list'),
  printReceipt: (data: unknown) => ipcRenderer.invoke('print:receipt', data),
  exportStockReport: (data: unknown) => ipcRenderer.invoke('print:export-report', data),
  getClients: () => ipcRenderer.invoke('db:get-clients'),
  getClient: (id: string) => ipcRenderer.invoke('db:get-client', id),
  createClient: (data: unknown) => ipcRenderer.invoke('db:create-client', data),
  updateClient: (id: string, data: unknown) => ipcRenderer.invoke('db:update-client', id, data),
  deleteClient: (id: string) => ipcRenderer.invoke('db:delete-client', id),
  getSuppliers: () => ipcRenderer.invoke('db:get-suppliers'),
  createSupplier: (data: unknown) => ipcRenderer.invoke('db:create-supplier', data),
  updateSupplier: (id: string, data: unknown) => ipcRenderer.invoke('db:update-supplier', id, data),
  deleteSupplier: (id: string) => ipcRenderer.invoke('db:delete-supplier', id),
  analyzeStock: () => ipcRenderer.invoke('stock:analyze'),
  confirmPurchase: (data: unknown) => ipcRenderer.invoke('db:confirm-purchase', data),
  restockProduct: (data: unknown) => ipcRenderer.invoke('db:restock-product', data),
  // Catégories
  getCategories: () => ipcRenderer.invoke('db:get-categories'),
  createCategory: (data: unknown) => ipcRenderer.invoke('db:create-category', data),
  updateCategory: (id: string, data: unknown) => ipcRenderer.invoke('db:update-category', id, data),
  deleteCategory: (id: string) => ipcRenderer.invoke('db:delete-category', id),
  // Dépenses
  getExpenses: () => ipcRenderer.invoke('db:get-expenses'),
  createExpense: (data: unknown) => ipcRenderer.invoke('db:create-expense', data),
  deleteExpense: (id: string) => ipcRenderer.invoke('db:delete-expense', id),
  // Cahier de caisse
  getRealTimeAccounting: (warehouseId: string) => ipcRenderer.invoke('db:get-real-time-accounting', warehouseId),
  getCashTransactions: (warehouseId: string) => ipcRenderer.invoke('db:get-cash-transactions', warehouseId),
  createCashTransaction: (data: unknown) => ipcRenderer.invoke('db:create-cash-transaction', data),
  deleteCashTransaction: (id: string) => ipcRenderer.invoke('db:delete-cash-transaction', id),
  exportCashReport: (data: unknown) => ipcRenderer.invoke('print:export-cash-report', data),
  // Mobile Money
  getMobileMoneyCells: (warehouseId: string, month: string) => ipcRenderer.invoke('db:get-mobile-money-cells', warehouseId, month),
  saveMobileMoneyCells: (warehouseId: string, month: string, cells: unknown) => ipcRenderer.invoke('db:save-mobile-money-cells', warehouseId, month, cells),
  getCanalPlusCells: (warehouseId: string, month: string) => ipcRenderer.invoke('db:get-canal-plus-cells', warehouseId, month),
  saveCanalPlusCells: (warehouseId: string, month: string, cells: unknown) => ipcRenderer.invoke('db:save-canal-plus-cells', warehouseId, month, cells),
  createCanalPlusSale: (data: unknown) => ipcRenderer.invoke('db:create-canal-plus-sale', data),
  getCanalPlusSales: (warehouseId: string, search?: string) => ipcRenderer.invoke('db:get-canal-plus-sales', warehouseId, search),
  getCanalPlusBalance: (warehouseId: string) => ipcRenderer.invoke('db:get-canal-plus-balance', warehouseId),
  getCanalPlusDailyBalance: (warehouseId: string) => ipcRenderer.invoke('db:get-canal-plus-daily-balance', warehouseId),
  // Magasin
  getMagasinStock: (warehouseId: string) => ipcRenderer.invoke('magasin:get-stock', warehouseId),
  transferMagasinToBoutique: (data: { productId: string; warehouseId: string; quantity: number }) => ipcRenderer.invoke('magasin:transfer-to-boutique', data),
  sendToMagasin: (data: { productId: string; warehouseId: string; quantity: number }) => ipcRenderer.invoke('magasin:send-to-magasin', data),
  receivePurchaseToMagasin: (data: { productId: string; warehouseId: string; quantity: number; unitPrice: number; paymentMethod?: string }) => ipcRenderer.invoke('magasin:receive-purchase', data),
  openFile: (filePath: string) => ipcRenderer.invoke('shell:open-file', filePath),
  exportRapportExcel: (params: unknown) => ipcRenderer.invoke('export:rapport-excel', params),
  exportMobileMoneyExcel: (params: unknown) => ipcRenderer.invoke('export:mobile-money-excel', params),
  exportCanalPlusExcel: (params: unknown) => ipcRenderer.invoke('export:canal-plus-excel', params),
  getGlobalStats: () => ipcRenderer.invoke('db:get-global-stats'),
  getDiscounts: (warehouseId?: string) => ipcRenderer.invoke('db:get-discounts', warehouseId),
  getAppSettings: () => ipcRenderer.invoke('db:get-app-settings'),
  updateAppSettings: (data: unknown) => ipcRenderer.invoke('db:update-app-settings', data),
  getMonthlyReport: (warehouseId: string, year: number, month: number) => ipcRenderer.invoke('db:get-monthly-report', warehouseId, year, month),
  exportTablePdf: (html: string, filename: string) => ipcRenderer.invoke('export:table-pdf', html, filename),
  // Updates
  checkForUpdates: () => ipcRenderer.send('update:check'),
  installUpdate: () => ipcRenderer.send('update:install'),
  onUpdateAvailable: (callback: () => void) => ipcRenderer.on('update:available', () => callback()),
  onUpdateDownloaded: (callback: () => void) => ipcRenderer.on('update:downloaded', () => callback()),
  onUpdateError: (callback: (error: any) => void) => ipcRenderer.on('update:error', (_e, err) => callback(err)),
}

contextBridge.exposeInMainWorld('api', api)
