import { contextBridge, ipcRenderer } from 'electron'

const api = {
  auth: {
    hasUsers: () => ipcRenderer.invoke('auth:has-users'),
    setupOwner: (data: unknown) => ipcRenderer.invoke('auth:setup-owner', data),
    login: (email: string, password: string) => ipcRenderer.invoke('auth:login', email, password),
    logout: () => ipcRenderer.invoke('auth:logout'),
    session: () => ipcRenderer.invoke('auth:session'),
    getUsers: () => ipcRenderer.invoke('auth:get-users'),
    createUser: (data: unknown) => ipcRenderer.invoke('auth:create-user', data),
    updateUser: (id: string, data: unknown) => ipcRenderer.invoke('auth:update-user', id, data),
    deleteUser: (id: string) => ipcRenderer.invoke('auth:delete-user', id),
    changePassword: (id: string, oldP: string, newP: string) => ipcRenderer.invoke('auth:change-password', id, oldP, newP),
    assignWarehouses: (userId: string, wIds: string[]) => ipcRenderer.invoke('auth:assign-warehouses', userId, wIds),
    setSecurityQuestion: (id: string, question: string, answer: string) => ipcRenderer.invoke('auth:set-security-question', id, question, answer),
    hasSecurityQuestion: (email: string) => ipcRenderer.invoke('auth:has-security-question', email),
    verifySecurityAnswer: (email: string, answer: string) => ipcRenderer.invoke('auth:verify-security-answer', email, answer),
    resetPassword: (email: string, newPassword: string) => ipcRenderer.invoke('auth:reset-password', email, newPassword),
    adminResetPassword: (id: string, newPassword: string) => ipcRenderer.invoke('auth:admin-reset-password', id, newPassword),
    generateRecoveryCode: (userId: string) => ipcRenderer.invoke('auth:generate-recovery-code', userId),
    hasRecoveryCode: (email: string) => ipcRenderer.invoke('auth:has-recovery-code', email),
    verifyRecoveryCode: (email: string, code: string) => ipcRenderer.invoke('auth:verify-recovery-code', email, code),
    verifyOwnerPassword: (password: string) => ipcRenderer.invoke('auth:verify-owner-password', password),
  },
  getProducts: (warehouseId?: string) => ipcRenderer.invoke('db:get-products', warehouseId),
  getProductByBarcode: (barcode: string, warehouseId?: string) => ipcRenderer.invoke('db:get-product-by-barcode', barcode, warehouseId),
  getProductDetails: (id: string) => ipcRenderer.invoke('db:get-product-details', id),
  createProduct: (data: unknown) => ipcRenderer.invoke('db:create-product', data),
  updateProduct: (id: string, data: unknown) => ipcRenderer.invoke('db:update-product', id, data),
  deleteProduct: (id: string) => ipcRenderer.invoke('db:delete-product', id),
  deleteAllProducts: (warehouseId?: string) => ipcRenderer.invoke('db:delete-all-products', warehouseId),

  createSale: (data: unknown) => ipcRenderer.invoke('db:create-sale', data),
  getSales: (clientId?: string, warehouseId?: string) => ipcRenderer.invoke('db:get-sales', clientId, warehouseId),
  getWarehouses: () => ipcRenderer.invoke('db:get-warehouses'),
  createWarehouse: (data: unknown) => ipcRenderer.invoke('db:create-warehouse', data),
  updateWarehouse: (id: string, data: unknown) => ipcRenderer.invoke('db:update-warehouse', id, data),
  deleteWarehouse: (id: string) => ipcRenderer.invoke('db:delete-warehouse', id),
  selectLogo: () => ipcRenderer.invoke('dialog:select-logo'),
  saveLogo: (sourcePath: string, warehouseId: string) => ipcRenderer.invoke('file:save-logo', sourcePath, warehouseId),
  saveInvoiceLogo: (sourcePath: string, warehouseId: string) => ipcRenderer.invoke('file:save-invoice-logo', sourcePath, warehouseId),
  saveProductImage: (sourcePath: string, productId: string) => ipcRenderer.invoke('file:save-product-image', sourcePath, productId),
  saveBookImage: (sourcePath: string, bookId: string) => ipcRenderer.invoke('file:save-book-image', sourcePath, bookId),
  getStockAlerts: () => ipcRenderer.invoke('db:get-stock-alerts'),
  getBookStockAlerts: () => ipcRenderer.invoke('db:get-book-stock-alerts'),
  getRupturedBooks: () => ipcRenderer.invoke('db:get-ruptured-books'),
  getPrinters: () => ipcRenderer.invoke('printer:list'),
  scanNetworkPrinters: () => ipcRenderer.invoke('printer:scan-network'),
  scanNearbyPrinters: () => ipcRenderer.invoke('printer:scan-nearby'),
  printReceipt: (data: unknown, config?: unknown) => ipcRenderer.invoke('print:receipt', data, config),
  printTestReceipt: (config?: unknown) => ipcRenderer.invoke('print:test', config),
  exportStockReport: (data: unknown) => ipcRenderer.invoke('print:export-report', data),
  getClients: (warehouseId?: string) => ipcRenderer.invoke('db:get-clients', warehouseId),
  searchClients: (query: string, warehouseId?: string) => ipcRenderer.invoke('db:search-clients', query, warehouseId),
  getClient: (id: string) => ipcRenderer.invoke('db:get-client', id),
  createClient: (data: unknown) => ipcRenderer.invoke('db:create-client', data),
  updateClient: (id: string, data: unknown) => ipcRenderer.invoke('db:update-client', id, data),
  deleteClient: (id: string) => ipcRenderer.invoke('db:delete-client', id),
  getSuppliers: (warehouseId?: string) => ipcRenderer.invoke('db:get-suppliers', warehouseId),
  createSupplier: (data: unknown) => ipcRenderer.invoke('db:create-supplier', data),
  updateSupplier: (id: string, data: unknown) => ipcRenderer.invoke('db:update-supplier', id, data),
  deleteSupplier: (id: string) => ipcRenderer.invoke('db:delete-supplier', id),
  analyzeStock: () => ipcRenderer.invoke('stock:analyze'),
  confirmPurchase: (data: unknown) => ipcRenderer.invoke('db:confirm-purchase', data),
  restockProduct: (data: unknown) => ipcRenderer.invoke('db:restock-product', data),
  // Catégories
  getCategories: (warehouseId?: string) => ipcRenderer.invoke('db:get-categories', warehouseId),
  createCategory: (data: unknown) => ipcRenderer.invoke('db:create-category', data),
  updateCategory: (id: string, data: unknown) => ipcRenderer.invoke('db:update-category', id, data),
  deleteCategory: (id: string) => ipcRenderer.invoke('db:delete-category', id),
  deleteAllCategories: () => ipcRenderer.invoke('db:delete-all-categories'),
  deleteEmptyCategories: () => ipcRenderer.invoke('db:delete-empty-categories'),
  clearCategoryProducts: (id: string) => ipcRenderer.invoke('db:clear-category-products', id),
  // Dépenses
  getExpenses: (warehouseId?: string) => ipcRenderer.invoke('db:get-expenses', warehouseId),
  createExpense: (data: unknown) => ipcRenderer.invoke('db:create-expense', data),
  deleteExpense: (id: string) => ipcRenderer.invoke('db:delete-expense', id),
  // Cahier de caisse
  getRealTimeAccounting: (warehouseId: string) => ipcRenderer.invoke('db:get-real-time-accounting', warehouseId),
  getCashTransactions: (warehouseId: string) => ipcRenderer.invoke('db:get-cash-transactions', warehouseId),
  createCashTransaction: (data: unknown) => ipcRenderer.invoke('db:create-cash-transaction', data),
  deleteCashTransaction: (id: string) => ipcRenderer.invoke('db:delete-cash-transaction', id),
  exportCashReport: (data: unknown) => ipcRenderer.invoke('print:export-cash-report', data),
  // Mobile Money
  getMobileMoneyCells: (warehouseId: string, month: string) => ipcRenderer.invoke('db:get-mobile-money-cells', warehouseId, month),
  saveMobileMoneyCells: (warehouseId: string, month: string, cells: unknown) => ipcRenderer.invoke('db:save-mobile-money-cells', warehouseId, month, cells),
  getCanalPlusCells: (warehouseId: string, month: string) => ipcRenderer.invoke('db:get-canal-plus-cells', warehouseId, month),
  saveCanalPlusCells: (warehouseId: string, month: string, cells: unknown) => ipcRenderer.invoke('db:save-canal-plus-cells', warehouseId, month, cells),
  createCanalPlusSale: (data: unknown) => ipcRenderer.invoke('db:create-canal-plus-sale', data),
  getCanalPlusSales: (warehouseId: string, search?: string) => ipcRenderer.invoke('db:get-canal-plus-sales', warehouseId, search),
  getCanalPlusBalance: (warehouseId: string) => ipcRenderer.invoke('db:get-canal-plus-balance', warehouseId),
  getCanalPlusDailyBalance: (warehouseId: string) => ipcRenderer.invoke('db:get-canal-plus-daily-balance', warehouseId),
  // Magasin
  getMagasinStock: (warehouseId: string) => ipcRenderer.invoke('magasin:get-stock', warehouseId),
  transferMagasinToBoutique: (data: { productId: string; warehouseId: string; quantity: number }) => ipcRenderer.invoke('magasin:transfer-to-boutique', data),
  sendToMagasin: (data: { productId: string; warehouseId: string; quantity: number }) => ipcRenderer.invoke('magasin:send-to-magasin', data),
  receivePurchaseToMagasin: (data: { productId: string; warehouseId: string; quantity: number; unitPrice: number; paymentMethod?: string }) => ipcRenderer.invoke('magasin:receive-purchase', data),
  openFile: (filePath: string) => ipcRenderer.invoke('shell:open-file', filePath),
  openExternal: (url: string) => ipcRenderer.invoke('shell:open-external', url),
  showItemInFolder: (filePath: string) => ipcRenderer.invoke('shell:show-item-in-folder', filePath),
  getOrdersDirectory: () => ipcRenderer.invoke('db:get-orders-dir'),
  getPurchaseOrders: () => ipcRenderer.invoke('db:get-purchase-orders'),
  getPurchaseOrder: (id: string) => ipcRenderer.invoke('db:get-purchase-order', id),
  updatePurchaseOrderStatus: (id: string, status: string) => ipcRenderer.invoke('db:update-purchase-order-status', id, status),
  deletePurchaseOrder: (id: string) => ipcRenderer.invoke('db:delete-purchase-order', id),
  exportPurchaseOrderPdf: (id: string) => ipcRenderer.invoke('db:export-purchase-order-pdf', id),
  exportPurchaseOrderExcel: (id: string) => ipcRenderer.invoke('db:export-purchase-order-excel', id),
  exportAllPurchaseOrdersExcel: () => ipcRenderer.invoke('db:export-all-purchase-orders-excel'),
  previewPdf: (filePath: string) => ipcRenderer.invoke('file:read-base64', filePath),
  exportRapportExcel: (params: unknown) => ipcRenderer.invoke('export:rapport-excel', params),
  exportProductsExcel: (warehouseId?: string) => ipcRenderer.invoke('export:products-excel', warehouseId),
  scanInvoicesByDate: (dateStr: string, warehouseId?: string) => ipcRenderer.invoke('scanner:scan-invoices-by-date', dateStr, warehouseId),
  exportScannedInvoicesPdf: (dateStr: string, warehouseId?: string) => ipcRenderer.invoke('scanner:export-scanned-invoices-pdf', dateStr, warehouseId),
  exportScannedInvoicesZip: (dateStr: string, warehouseId?: string) => ipcRenderer.invoke('scanner:export-scanned-invoices-zip', dateStr, warehouseId),
  getScannedDocuments: (dateStr?: string, warehouseId?: string, search?: string) => ipcRenderer.invoke('scan:get-documents', dateStr, warehouseId, search),
  createScannedDocument: (data: unknown) => ipcRenderer.invoke('scan:create-document', data),
  deleteScannedDocument: (id: string) => ipcRenderer.invoke('scan:delete-document', id),
  selectScanFile: () => ipcRenderer.invoke('scan:select-file'),
  exportMobileMoneyExcel: (params: unknown) => ipcRenderer.invoke('export:mobile-money-excel', params),
  exportCanalPlusExcel: (params: unknown) => ipcRenderer.invoke('export:canal-plus-excel', params),
  selectExcelFile: () => ipcRenderer.invoke('import:select-file'),
  previewExcel: (filePath: string, sheetName?: string) => ipcRenderer.invoke('import:preview-excel', filePath, sheetName),
  executeExcelImport: (params: unknown) => ipcRenderer.invoke('import:execute-excel', params),
  onImportProgress: (callback: (progress: unknown) => void) => {
    const handler = (_event: unknown, progress: unknown) => callback(progress)
    ipcRenderer.on('import:progress', handler)
    return () => {
      ipcRenderer.removeListener('import:progress', handler)
    }
  },
  getServiceSales: (warehouseId: string, search?: string) => ipcRenderer.invoke('db:get-service-sales', warehouseId, search),
  createServiceSale: (data: unknown) => ipcRenderer.invoke('db:create-service-sale', data),
  getGlobalStats: () => ipcRenderer.invoke('db:get-global-stats'),
  getDiscounts: (warehouseId?: string) => ipcRenderer.invoke('db:get-discounts', warehouseId),
  getDashboardStats: (period: string, warehouseId?: string) => ipcRenderer.invoke('db:dashboard-stats', period, warehouseId),
  // Agents
  getAgents: () => ipcRenderer.invoke('db:get-agents'),
  createAgent: (data: unknown) => ipcRenderer.invoke('db:create-agent', data),
  updateAgent: (id: string, data: unknown) => ipcRenderer.invoke('db:update-agent', id, data),
  deleteAgent: (id: string) => ipcRenderer.invoke('db:delete-agent', id),
  // Actions sur les factures
  validateSale: (saleId: string, complementAmount?: number) => ipcRenderer.invoke('db:validate-sale', saleId, complementAmount),
  paySale: (saleId: string) => ipcRenderer.invoke('db:pay-sale', saleId),
  cancelSale: (saleId: string) => ipcRenderer.invoke('db:cancel-sale', saleId),
  getPendingDeliveries: (warehouseId?: string) => ipcRenderer.invoke('db:get-pending-deliveries', warehouseId),
  deliverSale: (saleId: string, paymentMethod?: string) => ipcRenderer.invoke('db:deliver-sale', saleId, paymentMethod),
  updateDeliveryStatus: (saleId: string, deliveryStatus: string) => ipcRenderer.invoke('db:update-delivery-status', saleId, deliveryStatus),
  notifySaleClient: (saleId: string) => ipcRenderer.invoke('db:notify-sale-client', saleId),
  getAppSettings: () => ipcRenderer.invoke('db:get-app-settings'),
  updateAppSettings: (data: unknown) => ipcRenderer.invoke('db:update-app-settings', data),
  getMonthlyReport: (warehouseId: string, year: number, month: number) => ipcRenderer.invoke('db:get-monthly-report', warehouseId, year, month),
  exportTablePdf: (html: string, filename: string) => ipcRenderer.invoke('export:table-pdf', html, filename),
  // Librairie
  getClassLevels: (system?: string) => ipcRenderer.invoke('librairie:get-class-levels', system),
  getSubjects: (system?: string) => ipcRenderer.invoke('librairie:get-subjects', system),
  getBooks: (classLevelId?: string) => ipcRenderer.invoke('librairie:get-books', classLevelId),
  getBook: (id: string) => ipcRenderer.invoke('librairie:get-book', id),
  createBook: (data: any) => ipcRenderer.invoke('librairie:create-book', data),
  updateBook: (id: string, data: any) => ipcRenderer.invoke('librairie:update-book', id, data),
  deleteBook: (id: string) => ipcRenderer.invoke('librairie:delete-book', id),
  getBookStocks: (warehouseId: string, classLevelId?: string) => ipcRenderer.invoke('librairie:get-book-stocks', warehouseId, classLevelId),
  createBookStock: (data: any) => ipcRenderer.invoke('librairie:create-book-stock', data),
  updateBookStock: (id: string, data: any) => ipcRenderer.invoke('librairie:update-book-stock', id, data),
  createBookSale: (data: any) => ipcRenderer.invoke('librairie:create-book-sale', data),
  getBookSales: (warehouseId: string) => ipcRenderer.invoke('librairie:get-book-sales', warehouseId),
  getStudentTotals: (warehouseId: string, classLevelId: string) => ipcRenderer.invoke('librairie:get-student-totals', warehouseId, classLevelId),
  restockBook: (data: { bookId: string; warehouseId: string; quantity: number; purchasePrice?: number; editor?: string }) => ipcRenderer.invoke('librairie:restock-book', data),
  bulkRestockBooks: (data: unknown) => ipcRenderer.invoke('librairie:bulk-restock-books', data),
  bulkRestockProducts: (data: unknown) => ipcRenderer.invoke('db:bulk-restock-products', data),
  searchStudents: (query: string, warehouseId: string) => ipcRenderer.invoke('librairie:search-students', query, warehouseId),
  getStudentSummary: (studentName: string, classLevelId: string, warehouseId: string) => ipcRenderer.invoke('librairie:get-student-summary', studentName, classLevelId, warehouseId),
  updateBookAlertLimit: (bookId: string, warehouseId: string, alertLimit: number) => ipcRenderer.invoke('librairie:update-book-alert-limit', bookId, warehouseId, alertLimit),
  seedOfficialCurriculum: (warehouseId?: string) => ipcRenderer.invoke('librairie:seed-official-curriculum', warehouseId),
  // Mouvements de Stock (Stock Ledger)
  getStockMovements: (params: unknown) => ipcRenderer.invoke('stock:get-movements', params),
  // Sessions de Caisse (POS Clôture Z)
  getCurrentCashSession: (warehouseId: string) => ipcRenderer.invoke('cash:get-current-session', warehouseId),
  openCashSession: (params: unknown) => ipcRenderer.invoke('cash:open-session', params),
  closeCashSession: (params: unknown) => ipcRenderer.invoke('cash:close-session', params),
  getCashSessionHistory: (warehouseId: string, page?: number, pageSize?: number) => ipcRenderer.invoke('cash:get-session-history', warehouseId, page, pageSize),
  // Sauvegarde
  backupCreate: () => ipcRenderer.invoke('backup:create'),
  backupList: () => ipcRenderer.invoke('backup:list'),
  backupRestore: (filePath: string) => ipcRenderer.invoke('backup:restore', filePath),
  // Import / Export données .iventello
  dataExport: () => ipcRenderer.invoke('data:export'),
  dataImport: (archivePath: string, restoreDb: boolean) => ipcRenderer.invoke('data:import', archivePath, restoreDb),
  dataExportStats: () => ipcRenderer.invoke('data:export-stats'),
  dataSelectArchive: () => ipcRenderer.invoke('data:select-archive'),
  purgeDatabase: () => ipcRenderer.invoke('db:purge-database'),
  // Updates
  checkForUpdates: () => ipcRenderer.send('update:check'),
  installUpdate: () => ipcRenderer.send('update:install'),
  onUpdateAvailable: (callback: () => void) => {
    const handler = () => callback()
    ipcRenderer.on('update:available', handler)
    return () => ipcRenderer.removeListener('update:available', handler)
  },
  onUpdateDownloaded: (callback: () => void) => {
    const handler = () => callback()
    ipcRenderer.on('update:downloaded', handler)
    return () => ipcRenderer.removeListener('update:downloaded', handler)
  },
  onUpdateError: (callback: (error: any) => void) => {
    const handler = (_e: any, err: any) => callback(err)
    ipcRenderer.on('update:error', handler)
    return () => ipcRenderer.removeListener('update:error', handler)
  },
}

contextBridge.exposeInMainWorld('api', api)
