name: Build and Publish Electron App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build
        shell: bash
        run: npm run build

      - name: Package & Publish with electron-builder
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win --config electron-builder.yml --publish always
